name: Code quality checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  quality-checks:

    name: Quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install Dependencies
        run: |
          echo ${{ matrix.python-version }} > .python-version
          make setup

      - name: Check for typos
        run: make spellcheck

      - name: Check the code style
        run: make codestyle

      - name: Lint the code
        run: make lint

      - name: Type check the code
        run: make stricttypecheck

### code-checks.yaml ends here
